### ISSUE TITLE
Delayed log_flush and event loss over time

### ISSUE THREAD

**Issue by Jimjazzz** [osquery/osquery#7112]
# Bug report
While investigating IOPS issue in https://github.com/osquery/osquery/issues/7079 we performed long running tests, and we have seen that in Windows servers with a load of over 100 events/sec osquery reaches a point of degradation where it does not seem to be able to keep up, and logs start to be sent less often to the tls endpoint. This behavior cascades, as osquery has more and more events to send, so the used memory increases and not all events are sent.

The server is generating around 100 events/sec and sending the logs to a tls_endpoint. There is only 1 pack with two queries, that are executed every 30 seconds, and logger_tls_period is configured to 15 seconds:
```
SELECT *, "events_windows." || lower(source) || "." || eventid as __devoSubTag FROM windows_events WHERE source IN ('Application', 'Setup', 'Security', 'System');
SELECT *, "events_windows.other_sources" || "." || eventid as __devoSubTag FROM windows_events WHERE source Not IN ('Application', 'Setup', 'Security', 'System', 'Microsoft-Windows-PowerShell/Operational', 'Microsoft-Windows-PowerShell/Admin');
```
Attached is the `osquery_flags` output:
[Query Results_05-18-21 01-20-21.zip](https://github.com/osquery/osquery/files/6500988/Query.Results_05-18-21.01-20-21.zip)

### What operating system and version are you using?
Windows Server 2019

### What version of osquery are you using?
4.8.0

### What steps did you take to reproduce the issue?
1. Generate 100 events/second in a Windows server. We have seen the behavior in our customer environment, however, we emulate it in our labs using https://github.com/andrewkroh/goeventgen
2. Run osquery.
3. Wait for some time, it seems that the behavior appears after 1 or 2 hours running, but we have not seen much consistency. Sometimes it appears way before.

### What did you expect to see?
All events are correctly sent to the TLS endpoint.

### What did you see instead?
There is some loss of events.
Execution of the pack and log flush does not seem to happen honoring the times defined in the configuration.

### Other info
- I stopped osqueryd once it was in that state, and started it in verbose mode. Execution of the pack and `/api/v1/osquery/log ` request only seem to happen around 3 times in 15 minutes:
[devo-ua-agent-verbose_win1.zip](https://github.com/osquery/osquery/files/6501007/devo-ua-agent-verbose_win1.zip)

- Tested other two systems with 10 events/sec and 50 events/sec, and i have not seen this behavior. It would seem that the amount of events could be related with the issue.

**Comment by theopolis** [comment]
@Jimjazzz we merged another change that may effect the behavior you've reported: https://github.com/osquery/osquery/commit/a545374d448e9fb0bea89c88a2458e49d1afaf5a (build artifacts here: https://github.com/osquery/osquery/actions/runs/918253523)

You've been extremely helpful in testing, would you mind pulling the Windows build from the CI run and testing yet again?

**Comment by Jimjazzz** [comment]
I have some tests running, so far is looking promising but i need some more time to get valid results. 

As of now, i have been running a test during several hours and i can see that some of the events are being duplicated (it seems that it duplicates events every 30minutes...) but so far no event loss. 

Anyway, just a heads up. I will report with more detail and info tomorrow.

Thanks!

**Comment by Jimjazzz** [comment]
After some testing, i still see the event loss showing up.

I have set up two servers generating 100 emulated events/sec. 

There is 1 query in both servers executed every 60 secs: 
`SELECT *, "events_windows." || lower(source) || "." || eventid as __devoSubTag FROM windows_events WHERE lower(source) IN ('application', 'setup', 'security', 'system');`

Server 1: 
FleetDM 3.6.0 forwards results and status to our SIEM
events_expiry: 300
events_max: 500000
logger_tls_max_lines: 8192
logger_tls_period: 30

Server 2:
Default FleetDM 3.13 writes result and status to disk
events_expiry: 3600
events_max: 50000
logger_tls_max_lines: 8192
logger_tls_period: 10

I can see duplicated events and event loss in both cases.

In Server 1, it started duplicating events only , but at some point it also showed some event loss. If i look at the number of events ingested every minute i have a pattern like this:
![image](https://user-images.githubusercontent.com/73331488/121548776-9948c200-ca0d-11eb-86c9-e9ba7542ff72.png)

It shows a unstability period every 30 minutes approx, which usually translate in duplicated events, or more sporadically event loss. I do not see clearly the same pattern of the API log request or packs not being executed, so i think that the behavior may have actually changed.

In Server 2, i can see the same behavior, missing and repeated events are shown, but, in this case, osquery was killed by the watchdog and at some point the query was denylisted. I can see the message: `Found 278621 events for subscriber WindowsEventLogPublisher.windows_events` showin up many times...

I have attached results and status that fleetdm wrote to the disk in server 2 in:
[lost_events.zip](https://github.com/osquery/osquery/files/6632665/lost_events.zip)

I will continue some more testing tonight, also please let me know if you are looking for something as a result from the tests.

**Comment by theopolis** [comment]
Are these two servers running the version of osquery from the CI artifact link above?

**Comment by Jimjazzz** [comment]
Yes, both are running 4.8.0-38-ga545374d.

**Comment by Jimjazzz** [comment]
The server 1, that is sending to the SIEM, started to show the behavior reported initially where it seems that the log flush starts to get delayed. Following image is the number of events ingested every 1 minute:
![image](https://user-images.githubusercontent.com/73331488/121664588-e8433580-caa7-11eb-99f3-3c017b27de35.png)

The server 2, after yesterday results i did the following:
- Added the flag `--disable_watchdog=true` to avoid the watchdog interfering with the testing.
- Deleted DB and restarted osquery.
So far, it has been running all night without event loss and i see that the queries and log flushes are still being executed on-time. I will keep this test running longer see if the service degrades at some point. Attached here is the verbose log of this server. (got this from the stdout output):
[devo-ua-agent-verbose-newbuild.log](https://github.com/osquery/osquery/files/6637856/devo-ua-agent-verbose-newbuild.log)


I will run the server 1 in verbose mode and disable the watchdog to see if i can get the same behavior than server 2.

**Comment by Jimjazzz** [comment]
Continued tests during the weekend, show the following:

Server 1:
TLS endpoint: FleetDM 3.6.0 forwards results and status to our SIEM
osquery: 4.8.0-38-ga545374d
events_expiry: 300
events_max: 500000
logger_tls_max_lines: 8192
logger_tls_period: 30
disable_watchdog: true

Server 2:
TLS endpoint: Default FleetDM 3.13 writes result and status to disk
osquery: 4.8.0-38-ga545374d
events_expiry: 3600
events_max: 50000
logger_tls_max_lines: 8192
logger_tls_period: 10
disable_watchdog: true

In server 1, running with `--disable_watchdog=true` i can see that the data ingestion is way more stable.

Following is the ingestion grouped every 1 minute:
![image](https://user-images.githubusercontent.com/73331488/121886628-eaaac700-cd15-11eb-813d-dccb977587e2.png)

I still see some event loss (way lower than before), and some duplicated events. However, the pattern is definitely different and i do not see the timestamp delay and it seems that the pack is actually being executed and flushing on time.

In server 2, where the data is being written to disk in FleetDM, after disabling the watchdog, there has been no event loss and no duplicated events during the whole weekend. We can say this server test is successful after testing around 50 million events.

I am going to set the exact same settings in server 1, and try to settle if the difference in the behavior is due to configuration or something outside the osquery itself which is interfering with my testing observations.

Hope it helps.

**Comment by Jimjazzz** [comment]
Database also seems cleaner in Server2 than in Server 1.

Server1:
![image](https://user-images.githubusercontent.com/73331488/121902689-d7a0f280-cd27-11eb-835b-ebb18b7dfae5.png)

Server2:
![image](https://user-images.githubusercontent.com/73331488/121902515-ade7cb80-cd27-11eb-80ea-d7d51316bd9f.png)
