### ISSUE TITLE
Return appinstaller packages in a query of `programs`

### ISSUE THREAD

**Issue by kkirklandjc** [osquery/osquery#8001]
# Bug report

### What operating system and version are you using?
All Windows versions

### What version of osquery are you using?
5.7.0+

### What steps did you take to reproduce the issue?

Install a program via Microsoft Store or .appinstaller package
Execute the statement `select * from programs`
Observe that the installed program is not returned

### What did you expect to see?
All programs installed on the system should be returned.

osquery does not report software installations made from .appinstaller packages, therefore making it difficult for clients to maintain compliance about what is installed on their devices. This is likely because these programs do not write to the registry the same way that traditional executables do.

.appinstaller packages are not successfully queried by: https://github.com/osquery/osquery/blob/master/osquery/tables/system/windows/programs.cpp 

### What did you see instead?
appinstaller packages should be successfully queried in the programs table.

**Comment by devesh10s** [comment]
I tried the same way, 

What operating system and version are you using?
All Windows versions

What version of osquery are you using?
+------------+-------+----------+                                                                                                              | version    | build | platform |                                                                                                              +------------+-------+----------+                                                                                                              | 10.0.19045 | 19045 | windows  |                                                                                                              +------------+-------+----------+

What steps did you take to reproduce the issue?

I installed Netflix from Microsoft Store
Execute the statement select * from programs
Observe that the installed program is not returned

What did you expect to see?

All programs installed on the system should be returned.

osquery does not report software installations made from .appinstaller packages and .appx (AppxPackage) therefore making it difficult for clients to maintain compliance about what is installed on their devices. This is likely because these programs do not write to the registry the same way that traditional executables do.

What did you see instead?
osquery does not report software installations made from .appinstaller packages and .appx (AppxPackage)
appinstaller packages should be successfully queried in the programs table.

**Comment by directionless** [comment]
Nosing around a little, I think this is because the osquery implementation looks for programs by enumerating some common [registry locations](https://github.com/osquery/osquery/blob/c4a321fc9be790a75cabd8d7b2107b6b67d830f3/osquery/tables/system/windows/programs.cpp#L95-L106):
- `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall`
- `HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall`
- `HKEY_USERS\%\Software\Microsoft\Windows\CurrentVersion\Uninstall"

But, it looks like the Microsoft Store uses some other spots. I see `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\%` but I don't yet know if that's the right place, or how easily that can be converted

**Comment by rmulleyjc** [comment]
Is this issue resolved by https://github.com/osquery/osquery/pull/8585?

**Comment by getvictor** [comment]
PR #8585 partially addressed this by adding support for user-registered MSIX packages (queried from `HKEY_USERS\%\...\AppModel\Repository\Packages`). However, MSIX packages that are provisioned system-wide  but not yet launched by any user still don't appear in the programs table.                                                                                                                                                                                                                                                                        
                                                                              
 This is because provisioned packages are only staged in the machine-wide registry (`HKLM\...\Appx\AppxAllUserStore`) and aren't registered per-user until a user logs in and opens the app. The existing `genMsixPrograms()` code only looks at per-user paths.

  I'm going to take a look at extending `genMsixPrograms()` to also enumerate provisioned packages from the machine-wide registry and reuse the existing `AppxManifest.xml` parsing logic.
